job_descriptions = [
    "{0} is a professional cat juggler.",
    "{0} specializes in finding lost socks for a living.",
    "Meet {0}, the world's fastest typist... with their toes.",
    "{0} is a full-time bubble wrap popper and proud of it.",
    "When others go fishing, {0} fishes for compliments.",
    "Need a cloud whisperer? Look no further than {0}.",
    "{0} is a professional ice cream taster, certified in brain freeze prevention.",
    "Introducing {0}, the official snuggler of teddy bears.",
    "{0} moonlights as a professional unicorn groomer.",
    "As a certified professional nap-taker, {0} knows the best spots to snooze.",
    "Meet {0}, the world's greatest thumb wrestler.",
    "{0} turns pizza tossing into a mesmerizing art form.",
    "{0} can juggle flaming marshmallows blindfolded. It's a gift.",
    "Need someone to laugh at your jokes? {0} offers premium laughter services.",
    "{0} is a master in the delicate art of balloon animal psychology.",
    "Introducing {0}, a professional finger painter who's all grown up.",
    "When life gives lemons, {0} becomes a lemonade stand tycoon.",
    "{0} is a pro at avoiding cracks in the sidewalk, no really.",
    "{0} has achieved the world record for the most high-fives given in an hour.",
    "Meet {0}, the official tickler of funny bones worldwide.",
    "{0} is a professional bubble bath tester and takes their job seriously.",
    "Introducing {0}, a certified pirate treasure map interpreter.",
    "{0} is the reigning champion of extreme pillow fighting.",
    "When not busy, {0} practices interpretive dance for squirrels.",
    "{0} is a part-time cloud namer, adding personality to the sky.",
    "{0} moonlights as a professional bubble gum bubble blower.",
    "Introducing {0}, a master of assembling IKEA furniture... blindfolded.",
    "{0} offers premium services as a professional snowflake counter.",
    "Meet {0}, the world's fastest hopscotch skipper.",
    "{0} specializes in creating the most elaborate paper airplanes.",
    "When life gives them oranges, {0} makes orange juice. Clearly.",
    "{0} is a certified rainbow catcher, brightening days everywhere.",
    "Introducing {0}, the official jellybean sorter for the Candy Kingdom.",
    "{0} has perfected the art of parallel universe travel. Almost.",
    "Meet {0}, the world's greatest thumb war champion.",
    "{0} is a professional bubble wrap walker, making strides one pop at a time.",
    "{0} moonlights as a professional squirrel translator.",
    "Introducing {0}, a certified expert in untangling slinkies.",
    "{0} offers premium services as a professional hopscotch course designer.",
    "When not busy, {0} practices synchronized swimming with rubber duckies.",
    "{0} is a master at counting grains of sand on the beach. It's a talent.",
    "{0} is a professional ice cream cone juggler, cones and all.",
    "Meet {0}, the world's fastest snail racer.",
    "{0} specializes in alphabetizing soup cans with precision.",
    "When life gives them rubber ducks, {0} hosts epic bathtub regattas.",
    "Introducing {0}, a professional pillow fluffer for the most discerning sleepers.",
    "{0} has perfected the art of mind reading... well, almost.",
    "{0} is a certified expert in predicting the flavor of jellybeans by smell alone.",
    "Meet {0}, the official cloud shape cataloger.",
    "{0} moonlights as a professional hula hooper extraordinaire.",
    "Introducing {0}, a master at navigating through corn mazes with eyes closed.",
    "{0} offers premium services as a professional tic-tac-toe strategy consultant.",
    "When not busy, {0} practices extreme hula hooping for the Olympics.",
    "{0} is a certified bubble bath mixologist, creating bubbly wonders.",
    "{0} is a professional moonwalk tester and a smooth criminal at it.",
    "Meet {0}, the world's greatest marshmallow roaster, bonfires beware.",
    "{0} specializes in translating baby babble into eloquent speeches.",
    "When life gives them rubber bands, {0} becomes a rubber band guitar virtuoso.",
    "Introducing {0}, a professional bubble wrap popper with a black belt.",
    "{0} has perfected the art of invisibility... well, almost.",
    "{0} is a certified expert in reverse engineering pancakes.",
    "Meet {0}, the official tickle monster in residence.",
    "{0} moonlights as a professional kazoo symphony conductor.",
    "Introducing {0}, a master at building sandcastles in a hurricane.",
    "{0} offers premium services as a professional finger puppet therapist.",
    "When not busy, {0} practices synchronized skydiving with rubber chickens.",
    "{0} is a connoisseur of the finest invisible art, truly visionary.",
    "{0} is a professional paper airplane pilot, soaring to new heights.",
    "Meet {0}, the world's fastest turtle racer.",
    "{0} specializes in designing custom sock puppet wardrobes.",
    "When life gives them pineapples, {0} hosts extravagant tropical fruit fashion shows.",
    "Introducing {0}, a professional rubber duck wrangler for the world's toughest rodeos.",
    "{0} has perfected the art of speaking fluent penguin.",
    "{0} is a certified expert in deciphering the secret language of garden gnomes.",
    "Meet {0}, the official dragon tamer in training.",
    "{0} moonlights as a professional interpretive dance interpreter.",
    "Introducing {0}, a master of crafting paperclip sculptures of famous landmarks.",
    "{0} offers premium services as a professional kazoo karaoke coach.",
    "When not busy, {0} practices synchronized pogo sticking with kangaroos.",
    "{0} is a guru of potato chip fortune telling, a truly savory skill.",
    "{0} is a professional rubber band acrobat, stretching the limits of physics.",
    "Meet {0}, the world's fastest unicycle downhill racer.",
    "{0} specializes in creating avant-garde hairstyles for garden gnomes.",
    "When life gives them rubber chickens, {0} hosts sold-out stand-up comedy shows.",
    "Introducing {0}, a professional pancake flipper with Olympic aspirations.",
    "{0} has perfected the art of translating Morse code through interpretive dance.",
    "{0} is a certified expert in composing sonnets for squirrels.",
    "Meet {0}, the official bubble wrap ballet choreographer.",
    "{0} moonlights as a professional kite flyer in hurricane-prone areas.",
    "Introducing {0}, a master at knitting sweaters for cacti.",
    "{0} offers premium services as a professional interpretive cloud painter.",
    "{0} is a professional llama whisperer, communicating through stylish neckwear.",
    "Introducing {0}, a master at parallel parking monster trucks.",
    "{0} moonlights as a professional penguin personal trainer.",
    "{0} specializes in decoding the cryptic language of garden gnomes.",
    "{0} is a certified expert in teaching synchronized swimming to goldfish.",
    "Meet {0}, the official toe wrestler of the underground toe wrestling circuit.",
    "{0} offers premium services as a professional bubble wrap fashion designer.",
    "When not busy, {0} practices extreme origami with 2-inch square paper.",
    "{0} is a professional squirrel obstacle course designer, complete with tiny hurdles.",
    "Introducing {0}, a master at yodeling while underwater.",
    "{0} has perfected the art of solving Rubik's cubes with their nose.",
    "{0} is a certified expert in predicting the weather based on cloud formations in coffee.",
    "Meet {0}, the official under-the-bed monster negotiator.",
    "{0} moonlights as a professional pogo stick tester for aspiring kangaroos.",
    "{0} specializes in crafting intricate sand mandalas for crabs.",
    "{0} is a certified expert in interpretive dance for shy garden gnomes.",
    "{0} is a professional puddle jumper, leaping over rainwater with grace.",
    "Introducing {0}, a master at balancing tea cups on their nose.",
    "{0} offers premium services as a professional squirrel fashion consultant.",
    "When not busy, {0} practices extreme juggling with watermelons.",
    "{0} is a professional banana peel slip-and-fall stunt double.",
    "Meet {0}, the official napkin folding instructor for high-class squirrels.",
    "{0} moonlights as a professional hula hooper on unicycles.",
    "{0} specializes in composing epic ballads for garden gnomes.",
    "{0} is a certified expert in teaching breakdancing to flamingos.",
    "Introducing {0}, a master at interpretive dancing with their shadow.",
    "{0} offers premium services as a professional bubble gum sculpture artist.",
    "{0} is a professional snowflake catcher during summer heatwaves.",
    "When not busy, {0} practices synchronized swimming with rubber sharks.",
    "{0} is a certified expert in underwater basket weaving with jellyfish tentacles.",
    "Meet {0}, the official tickle tester for baby kittens.",
    "{0} moonlights as a professional moon bounce tester on trampolines.",
    "{0} specializes in coaching competitive pillow fight teams.",
    "{0} is a certified expert in teaching penguins to fly... in their dreams.",
    "{0} is a professional bubble wrap maze designer, challenging adventurers everywhere.",
    "Introducing {0}, a master at solving riddles in whale songs.",
    "{0} offers premium services as a professional squirrel language translator.",
    "When not busy, {0} practices tightrope walking with dental floss.",
    "{0} is a professional shadow puppeteer for sunsets.",
    "Meet {0}, the official fog sculptor, shaping mist into intricate designs.",
    "{0} moonlights as a professional unicycle juggler at stoplights.",
    "{0} specializes in crafting gourmet meals for action figures.",
    "{0} is a certified expert in teaching synchronized swimming to rubber ducks.",
    "{0} is a professional bubble wrap enthusiast, popping joy into the world.",
    "Introducing {0}, a master at underwater knitting with mermaids.",
    "{0} offers premium services as a professional squirrel life coach.",
    "When not busy, {0} practices synchronized ballet with flamingos.",
    "{0} is a certified expert in extreme teacup stacking.",
    "{0} is a professional fortune teller for garden gnomes.",
    "Meet {0}, the official squirrel wardrobe stylist, keeping tails fabulous.",
    "{0} moonlights as a professional rubber chicken ventriloquist.",
    "{0} specializes in composing operas for opera-singing whales.",
    "{0} is a certified expert in teaching squirrels to water ski.",
    "{0} is a professional moon rock polisher, making lunar bling shine.",
    "Introducing {0}, a master at interpretive dance with traffic signals.",
    "{0} offers premium services as a professional cloud whisperer.",
    "When not busy, {0} practices synchronized roller skating with roller derby queens.",
    "{0} is a professional bubble wrap castle architect.",
    "{0} moonlights as a professional stilt walker for garden gnomes.",
    "{0} specializes in training crows for synchronized sky performances.",
    "{0} is a certified expert in deciphering ancient hieroglyphs on candy wrappers.",
    "{0} is a professional rainbow chaser, painting the sky with vibrant hues.",
    "Meet {0}, the official rubber band orchestra conductor.",
    "{0} moonlights as a professional flamingo tamer.",
    "{0} offers premium services as a professional squirrel comedian.",
    "When not busy, {0} practices synchronized interpretive dance with wind turbines.",
    "{0} is a certified expert in teaching squirrels to dance the cha-cha.",
    "{0} is a professional cloud shape shifter, turning clouds into whimsical creatures.",
    "Introducing {0}, a master at interpretive dance with tumbleweeds.",
    "{0} specializes in composing symphonies for underwater harmonicas.",
    "{0} is a certified expert in training dolphins to moonwalk.",
    "{0} is a professional shadow puppeteer for campfires.",
    "Meet {0}, the official squirrel choreographer, mastering tree-bound routines.",
    "{0} moonlights as a professional bubble wrap composer.",
    "{0} offers premium services as a professional squirrel fashion designer.",
    "When not busy, {0} practices synchronized breakdancing with breakdancing beetles.",
    "{0} is a certified expert in teaching squirrels to do the limbo.",
    "{0} is a professional cloud surfer, riding waves through the sky.",
    "Introducing {0}, a master at interpretive dance with tumble dryers.",
    "{0} specializes in composing symphonies for underwater tubas.",
    "{0} is a certified expert in teaching seahorses to square dance.",
    "{0} is a professional firefly choreographer, creating mesmerizing light shows.",
    "Meet {0}, the official squirrel acrobat, flipping through trees with finesse.",
    "{0} moonlights as a professional bubble wrap sculptor.",
    "{0} offers premium services as a professional squirrel motivational speaker.",
    "When not busy, {0} practices synchronized interpretive dance with whirlwinds.",
    "{0} is a certified expert in training ants to perform synchronized swimming.",
    "{0} is a professional cloud graffiti artist, tagging the sky with creativity.",
    "Introducing {0}, a master at interpretive dance with tumbleweeds.",
    "{0} specializes in composing symphonies for underwater piccolos.",
    "{0} is a certified expert in teaching seals to tango.",
    "{0} is a professional shadow puppeteer for campfires."]
