job_descriptions = [
    "{0} is a professional cat juggler.",
    "{0} specializes in finding lost socks for a living.",
    "Meet {0}, the world's fastest typist... with their toes.",
    "{0} is a full-time bubble wrap popper and proud of it.",
    "When others go fishing, {0} fishes for compliments.",
    "Need a cloud whisperer? Look no further than {0}.",
    "{0} is a professional ice cream taster, certified in brain freeze prevention.",
    "Introducing {0}, the official snuggler of teddy bears.",
    "{0} moonlights as a professional unicorn groomer.",
    "As a certified professional nap-taker, {0} knows the best spots to snooze.",
    "Meet {0}, the world's greatest thumb wrestler.",
    "{0} turns pizza tossing into a mesmerizing art form.",
    "{0} can juggle flaming marshmallows blindfolded. It's a gift.",
    "Need someone to laugh at your jokes? {0} offers premium laughter services.",
    "{0} is a master in the delicate art of balloon animal psychology.",
    "Introducing {0}, a professional finger painter who's all grown up.",
    "When life gives lemons, {0} becomes a lemonade stand tycoon.",
    "{0} is a pro at avoiding cracks in the sidewalk, no really.",
    "{0} has achieved the world record for the most high-fives given in an hour.",
    "Meet {0}, the official tickler of funny bones worldwide.",
    "{0} is a professional bubble bath tester and takes their job seriously.",
    "Introducing {0}, a certified pirate treasure map interpreter.",
    "{0} is the reigning champion of extreme pillow fighting.",
    "When not busy, {0} practices interpretive dance for squirrels.",
    "{0} is a part-time cloud namer, adding personality to the sky.",
    "{0} moonlights as a professional bubble gum bubble blower.",
    "Introducing {0}, a master of assembling IKEA furniture... blindfolded.",
    "{0} offers premium services as a professional snowflake counter.",
    "Meet {0}, the world's fastest hopscotch skipper.",
    "{0} specializes in creating the most elaborate paper airplanes.",
    "When life gives them oranges, {0} makes orange juice. Clearly.",
    "{0} is a certified rainbow catcher, brightening days everywhere.",
    "Introducing {0}, the official jellybean sorter for the Candy Kingdom.",
    "{0} has perfected the art of parallel universe travel. Almost.",
    "Meet {0}, the world's greatest thumb war champion.",
    "{0} is a professional bubble wrap walker, making strides one pop at a time.",
    "{0} moonlights as a professional squirrel translator.",
    "Introducing {0}, a certified expert in untangling slinkies.",
    "{0} offers premium services as a professional hopscotch course designer.",
    "When not busy, {0} practices synchronized swimming with rubber duckies.",
    "{0} is a master at counting grains of sand on the beach. It's a talent.",
    "{0} is a professional ice cream cone juggler, cones and all.",
    "Meet {0}, the world's fastest snail racer.",
    "{0} specializes in alphabetizing soup cans with precision.",
    "When life gives them rubber ducks, {0} hosts epic bathtub regattas.",
    "Introducing {0}, a professional pillow fluffer for the most discerning sleepers.",
    "{0} has perfected the art of mind reading... well, almost.",
    "{0} is a certified expert in predicting the flavor of jellybeans by smell alone.",
    "Meet {0}, the official cloud shape cataloger.",
    "{0} moonlights as a professional hula hooper extraordinaire.",
    "Introducing {0}, a master at navigating through corn mazes with eyes closed.",
    "{0} offers premium services as a professional tic-tac-toe strategy consultant.",
    "When not busy, {0} practices extreme hula hooping for the Olympics.",
    "{0} is a certified bubble bath mixologist, creating bubbly wonders.",
    "{0} is a professional moonwalk tester and a smooth criminal at it.",
    "Meet {0}, the world's greatest marshmallow roaster, bonfires beware.",
    "{0} specializes in translating baby babble into eloquent speeches.",
    "When life gives them rubber bands, {0} becomes a rubber band guitar virtuoso.",
    "Introducing {0}, a professional bubble wrap popper with a black belt.",
    "{0} has perfected the art of invisibility... well, almost.",
    "{0} is a certified expert in reverse engineering pancakes.",
    "Meet {0}, the official tickle monster in residence.",
    "{0} moonlights as a professional kazoo symphony conductor.",
    "Introducing {0}, a master at building sandcastles in a hurricane.",
    "{0} offers premium services as a professional finger puppet therapist.",
    "When not busy, {0} practices synchronized skydiving with rubber chickens.",
    "{0} is a connoisseur of the finest invisible art, truly visionary.",
    "{0} is a professional paper airplane pilot, soaring to new heights.",
    "Meet {0}, the world's fastest turtle racer.",
    "{0} specializes in designing custom sock puppet wardrobes.",
    "When life gives them pineapples, {0} hosts extravagant tropical fruit fashion shows.",
    "Introducing {0}, a professional rubber duck wrangler for the world's toughest rodeos.",
    "{0} has perfected the art of speaking fluent penguin.",
    "{0} is a certified expert in deciphering the secret language of garden gnomes.",
    "Meet {0}, the official dragon tamer in training.",
    "{0} moonlights as a professional interpretive dance interpreter.",
    "Introducing {0}, a master of crafting paperclip sculptures of famous landmarks.",
    "{0} offers premium services as a professional kazoo karaoke coach.",
    "When not busy, {0} practices synchronized pogo sticking with kangaroos.",
    "{0} is a guru of potato chip fortune telling, a truly savory skill.",
    "{0} is a professional rubber band acrobat, stretching the limits of physics.",
    "Meet {0}, the world's fastest unicycle downhill racer.",
    "{0} specializes in creating avant-garde hairstyles for garden gnomes.",
    "When life gives them rubber chickens, {0} hosts sold-out stand-up comedy shows.",
    "Introducing {0}, a professional pancake flipper with Olympic aspirations.",
    "{0} has perfected the art of translating Morse code through interpretive dance.",
    "{0} is a certified expert in composing sonnets for squirrels.",
    "Meet {0}, the official bubble wrap ballet choreographer.",
    "{0} moonlights as a professional kite flyer in hurricane-prone areas.",
    "Introducing {0}, a master at knitting sweaters for cacti.",
    "{0} offers premium services as a professional interpretive cloud painter.",
    "{0} is a professional llama whisperer, communicating through stylish neckwear.",
    "Introducing {0}, a master at parallel parking monster trucks.",
    "{0} moonlights as a professional penguin personal trainer.",
    "{0} specializes in decoding the cryptic language of garden gnomes.",
    "{0} is a certified expert in teaching synchronized swimming to goldfish.",
    "Meet {0}, the official toe wrestler of the underground toe wrestling circuit.",
    "{0} offers premium services as a professional bubble wrap fashion designer.",
    "When not busy, {0} practices extreme origami with 2-inch square paper.",
    "{0} is a professional squirrel obstacle course designer, complete with tiny hurdles.",
    "Introducing {0}, a master at yodeling while underwater.",
    "{0} has perfected the art of solving Rubik's cubes with their nose.",
    "{0} is a certified expert in predicting the weather based on cloud formations in coffee.",
    "Meet {0}, the official under-the-bed monster negotiator.",
    "{0} moonlights as a professional pogo stick tester for aspiring kangaroos.",
    "{0} specializes in crafting intricate sand mandalas for crabs.",
    "{0} is a certified expert in interpretive dance for shy garden gnomes.",
    "{0} is a professional puddle jumper, leaping over rainwater with grace.",
    "Introducing {0}, a master at balancing tea cups on their nose.",
    "{0} offers premium services as a professional squirrel fashion consultant.",
    "When not busy, {0} practices extreme juggling with watermelons.",
    "{0} is a professional banana peel slip-and-fall stunt double.",
    "Meet {0}, the official napkin folding instructor for high-class squirrels.",
    "{0} moonlights as a professional hula hooper on unicycles.",
    "{0} specializes in composing epic ballads for garden gnomes.",
    "{0} is a certified expert in teaching breakdancing to flamingos.",
    "Introducing {0}, a master at interpretive dancing with their shadow.",
    "{0} offers premium services as a professional bubble gum sculpture artist.",
    "{0} is a professional snowflake catcher during summer heatwaves.",
    "When not busy, {0} practices synchronized swimming with rubber sharks.",
    "{0} is a certified expert in underwater basket weaving with jellyfish tentacles.",
    "Meet {0}, the official tickle tester for baby kittens.",
    "{0} moonlights as a professional moon bounce tester on trampolines.",
    "{0} specializes in coaching competitive pillow fight teams.",
    "{0} is a certified expert in teaching penguins to fly... in their dreams.",
    "{0} is a professional bubble wrap maze designer, challenging adventurers everywhere.",
    "Introducing {0}, a master at solving riddles in whale songs.",
    "{0} offers premium services as a professional squirrel language translator.",
    "When not busy, {0} practices tightrope walking with dental floss.",
    "{0} is a professional shadow puppeteer for sunsets.",
    "Meet {0}, the official fog sculptor, shaping mist into intricate designs.",
    "{0} moonlights as a professional unicycle juggler at stoplights.",
    "{0} specializes in crafting gourmet meals for action figures.",
    "{0} is a certified expert in teaching synchronized swimming to rubber ducks.",
    "{0} is a professional bubble wrap enthusiast, popping joy into the world.",
    "Introducing {0}, a master at underwater knitting with mermaids.",
    "{0} offers premium services as a professional squirrel life coach.",
    "When not busy, {0} practices synchronized ballet with flamingos.",
    "{0} is a certified expert in extreme teacup stacking.",
    "{0} is a professional fortune teller for garden gnomes.",
    "Meet {0}, the official squirrel wardrobe stylist, keeping tails fabulous.",
    "{0} moonlights as a professional rubber chicken ventriloquist.",
    "{0} specializes in composing operas for opera-singing whales.",
    "{0} is a certified expert in teaching squirrels to water ski.",
    "{0} is a professional moon rock polisher, making lunar bling shine.",
    "Introducing {0}, a master at interpretive dance with traffic signals.",
    "{0} offers premium services as a professional cloud whisperer.",
    "When not busy, {0} practices synchronized roller skating with roller derby queens.",
    "{0} is a professional bubble wrap castle architect.",
    "{0} moonlights as a professional stilt walker for garden gnomes.",
    "{0} specializes in training crows for synchronized sky performances.",
    "{0} is a certified expert in deciphering ancient hieroglyphs on candy wrappers.",
    "{0} is a professional rainbow chaser, painting the sky with vibrant hues.",
    "Meet {0}, the official rubber band orchestra conductor.",
    "{0} moonlights as a professional flamingo tamer.",
    "{0} offers premium services as a professional squirrel comedian.",
    "When not busy, {0} practices synchronized interpretive dance with wind turbines.",
    "{0} is a certified expert in teaching squirrels to dance the cha-cha.",
    "{0} is a professional cloud shape shifter, turning clouds into whimsical creatures.",
    "Introducing {0}, a master at interpretive dance with tumbleweeds.",
    "{0} specializes in composing symphonies for underwater harmonicas.",
    "{0} is a certified expert in training dolphins to moonwalk.",
    "{0} is a professional shadow puppeteer for campfires.",
    "Meet {0}, the official squirrel choreographer, mastering tree-bound routines.",
    "{0} moonlights as a professional bubble wrap composer.",
    "{0} offers premium services as a professional squirrel fashion designer.",
    "When not busy, {0} practices synchronized breakdancing with breakdancing beetles.",
    "{0} is a certified expert in teaching squirrels to do the limbo.",
    "{0} is a professional cloud surfer, riding waves through the sky.",
    "Introducing {0}, a master at interpretive dance with tumble dryers.",
    "{0} specializes in composing symphonies for underwater tubas.",
    "{0} is a certified expert in teaching seahorses to square dance.",
    "{0} is a professional firefly choreographer, creating mesmerizing light shows.",
    "Meet {0}, the official squirrel acrobat, flipping through trees with finesse.",
    "{0} moonlights as a professional bubble wrap sculptor.",
    "{0} offers premium services as a professional squirrel motivational speaker.",
    "When not busy, {0} practices synchronized interpretive dance with whirlwinds.",
    "{0} is a certified expert in training ants to perform synchronized swimming.",
    "{0} is a professional cloud graffiti artist, tagging the sky with creativity.",
    "Introducing {0}, a master at interpretive dance with tumbleweeds.",
    "{0} specializes in composing symphonies for underwater piccolos.",
    "{0} is a certified expert in teaching seals to tango.",
    "{0} is a professional shadow puppeteer for campfires."]

fake_robbery_scenarios = [
    ("{0} attempted to steal {1}'s collection of rubber duckies but got chased away by a squirrel.", False),
    ("In a daring heist, {0} tried to snatch {1}'s cookie jar, but it turned out to be a decoy filled with broccoli.",
     False),
    ("{0} disguised themselves as a penguin to swipe {1}'s snow cone, but slipped on a banana peel instead.", False),
    ("During the grand heist, {0} went after {1}'s invisible treasure chest and accidentally knocked over a lamp.",
     False),
    ("{0} dressed up as a ninja to nab {1}'s pillow, only to realize it was a marshmallow-filled decoy.", False),
    ("In an audacious move, {0} attempted to steal {1}'s fake gold coins, but they were just chocolate wrappers.",
     False),
    ("{0} plotted to take {1}'s invisible sandwich, but their getaway vehicle was a slow-moving turtle.", False),
    (
        "During the master plan, {0} aimed to snatch {1}'s secret banana stash, but got caught in a game of hide-and-seek.",
        False),
    ("{0} hatched a cunning scheme to steal {1}'s rubber chicken collection, but tripped over a feather.", False),
    ("In a comedic twist, {0} tried to take {1}'s invisible pet rock, only to discover it was made of air.", False),
    ("{0} schemed to nab {1}'s fake mustache collection, but got tangled in the disguise.", False),
    ("During the elaborate caper, {0} attempted to steal {1}'s bubble wrap, but ended up popping half of it.", False),
    ("{0} orchestrated a plan to take {1}'s toy spaceship, but got stuck in a pile of building blocks.", False),
    ("In a daring plot, {0} tried to snatch {1}'s invisible hat, but was foiled by a gust of wind.", False),
    ("{0} disguised themselves as a superhero to nab {1}'s rubber band ball, but it bounced away.", False),
    ("During the grand heist, {0} went after {1}'s pretend pirate treasure, only to find plastic coins.", False),
    ("{0} plotted to steal {1}'s cardboard castle, but got trapped in a cardboard dragon's jaws.", False),
    ("In an audacious move, {0} attempted to take {1}'s collection of invisible stamps, but lost their map.", False),
    ("{0} dressed up as a cowboy to snatch {1}'s imaginary lasso, but tripped over a tumbleweed.", False),
    ("During the master plan, {0} aimed to steal {1}'s toy crown, but got stuck in a toy robot's grip.", False),
    ("{0} hatched a cunning scheme to take {1}'s fake treasure map, but got lost in the crayon-drawn maze.", False),
    ("In a comedic twist, {0} tried to nab {1}'s invisible sunglasses, but couldn't find them.", False),
    ("{0} schemed to steal {1}'s toy race car, but accidentally triggered a toy car avalanche.", False),
    (
        "During the elaborate caper, {0} attempted to snatch {1}'s pretend detective kit, but left a trail of toy footprints.",
        False),
    ("{0} orchestrated a plan to take {1}'s collection of toy bugs, but they scattered everywhere.", False),
    ("In a daring plot, {0} tried to steal {1}'s imaginary friend's favorite toy, but it vanished.", False),
    ("{0} disguised themselves as a magician to nab {1}'s magic wand, but it turned into a rubber chicken.", False),
    ("During the grand heist, {0} went after {1}'s toy telescope, but saw only clouds.", False),
    ("{0} plotted to steal {1}'s invisible jetpack, but ended up floating away.", False),
    (
        "In an audacious move, {0} attempted to take {1}'s pretend crown, but got caught in a paper crown's strap.",
        False),
    ("{0} dressed up as a spy to snatch {1}'s toy spy gear, but triggered all the alarms.", False),
    (
        "During the master plan, {0} aimed to steal {1}'s collection of toy dinosaurs, but they came to life and chased them.",
        False),
    ("{0} hatched a cunning scheme to nab {1}'s invisible ninja sword, but it turned into a pool noodle.", False),
    ("In a comedic twist, {0} tried to steal {1}'s magic potion kit, but spilled it all over themselves.", False),
    ("{0} schemed to take {1}'s toy rocket, but got stuck in the launch pad.", False),
    ("During the elaborate caper, {0} attempted to snatch {1}'s superhero cape, but got tangled in it.", False),
    ("{0} orchestrated a plan to steal {1}'s collection of toy robots, but they rebelled against them.", False),
    ("In a daring plot, {0} tried to steal {1}'s invisible time machine, but ended up in a cardboard box.", False),
    ("{0} disguised themselves as a pirate to nab {1}'s toy treasure chest, but it was filled with candy.", False),
    ("During the grand heist, {0} went after {1}'s pretend chef kit, but ended up covered in toy spaghetti.", False),
    ("{0} plotted to steal {1}'s toy magic carpet, but it got caught on a doorknob.", False),
    (
        "In an audacious move, {0} attempted to take {1}'s collection of toy trains, but they went off the tracks.",
        False),
    ("{0} dressed up as a wizard to snatch {1}'s magic wand, but turned themselves into a frog.", False),
    ("During the master plan, {0} aimed to steal {1}'s invisible superhero suit, but it was too slippery.", False),
    ("{0} hatched a cunning scheme to nab {1}'s toy pirate ship, but it sailed away in a tub.", False),
    ("In a comedic twist, {0} tried to steal {1}'s toy detective magnifying glass, but looked the wrong way.", False),
    ("{0} schemed to take {1}'s collection of toy aliens, but they zapped them with toy ray guns.", False),
    ("During the elaborate caper, {0} attempted to snatch {1}'s pretend knight armor, but got stuck in it.", False),
    ("{0} orchestrated a plan to steal {1}'s toy space shuttle, but it crash-landed on a book.", False),
    ("In a daring plot, {0} tried to steal {1}'s invisible pirate treasure, but it was guarded by an invisible dragon.",
     False),
    ("{0} plotted to steal {1}'s toy race car track, but the cars kept crashing into each other.", False),
    (
        "In an audacious move, {0} attempted to take {1}'s collection of toy animals, but they all escaped to the backyard.",
        False),
    ("{0} dressed up as a pilot to snatch {1}'s toy airplane, but it got stuck in a tree.", False),
    ("During the master plan, {0} aimed to steal {1}'s invisible knight sword, but it was too heavy.", False),
    ("{0} hatched a cunning scheme to nab {1}'s toy firefighter hat, but got caught in a game of 'put out the fire.'",
     False),
    ("In a comedic twist, {0} tried to steal {1}'s toy doctor kit, but ended up with a toy thermometer in their ear.",
     False),
    ("{0} schemed to take {1}'s collection of toy construction vehicles, but they all started 'building' a sandcastle.",
     False),
    (
        "During the elaborate caper, {0} attempted to snatch {1}'s pretend scientist goggles, but they were stuck to their forehead.",
        False),
    ("{0} orchestrated a plan to steal {1}'s toy robot dog, but it kept chasing its tail.", False),
    ("In a daring plot, {0} tried to steal {1}'s invisible superhero cape, but it turned into a blanket.", False),
    ("{0} disguised themselves as a chef to nab {1}'s toy kitchen set, but got tangled in a spaghetti mess.", False),
    ("During the grand heist, {0} went after {1}'s pretend explorer backpack, but got lost in the living room.", False),
    ("{0} plotted to steal {1}'s toy spy glasses, but couldn't see a thing through them.", False),
    (
        "In an audacious move, {0} attempted to take {1}'s collection of toy musical instruments, but all they got was a kazoo.",
        False),
    ("{0} dressed up as a superhero to snatch {1}'s toy mask, but it got stuck on their head.", False),
    ("During the master plan, {0} aimed to steal {1}'s invisible pirate hat, but it vanished into thin air.", False),
    ("{0} hatched a cunning scheme to nab {1}'s toy firefighter hose, but it squirted them instead.", False),
    ("In a comedic twist, {0} tried to steal {1}'s toy magician's hat, but pulled out a rubber chicken.", False),
    ("{0} schemed to take {1}'s collection of toy sports equipment, but they all bounced away.", False),
    ("During the elaborate caper, {0} attempted to snatch {1}'s pretend artist beret, but it got stuck in their hair.",
     False),
    ("{0} orchestrated a plan to steal {1}'s toy chef apron, but got tangled in the strings.", False),
    ("In a daring plot, {0} tried to steal {1}'s invisible astronaut helmet, but it was just a clear bowl.", False),
    ("{0} disguised themselves as a spy to nab {1}'s toy magnifying glass, but it showed everything upside down.",
     False),
    (
        "During the grand heist, {0} went after {1}'s pretend scientist lab coat, but spilled fake potions all over themselves.",
        False),
    ("{0} plotted to steal {1}'s toy firefighter boots, but they were too big to fit.", False),
    ("In an audacious move, {0} attempted to take {1}'s collection of toy building blocks, but they toppled over.",
     False),
    ("{0} dressed up as a magician to snatch {1}'s toy wand, but it turned into a rubber chicken.", False),
    ("During the master plan, {0} aimed to steal {1}'s invisible explorer hat, but it was see-through.", False),
    ("{0} hatched a cunning scheme to nab {1}'s toy detective pipe, but blew bubbles instead.", False),
    ("In a comedic twist, {0} tried to steal {1}'s toy rock collection, but they all rolled away.", False),
    ("{0} schemed to take {1}'s collection of toy animal figures, but they all went on strike.", False),
    ("During the elaborate caper, {0} attempted to snatch {1}'s pretend chef spoon, but stirred up a mess.", False),
    ("{0} orchestrated a plan to steal {1}'s toy astronaut helmet, but it got stuck on their foot.", False),
    ("In a daring plot, {0} tried to steal {1}'s invisible scientist glasses, but they couldn't see through them.",
     False),
    ("{0} disguised themselves as a superhero to nab {1}'s toy cape, but it was too short.", False),
    ("During the grand heist, {0} went after {1}'s pretend artist paintbrush, but ended up with colorful fingers.",
     False),
    ("{0} plotted to steal {1}'s toy pirate hat, but it blew away in the wind.", False),
    ("In an audacious move, {0} attempted to take {1}'s toy firefighter helmet, but got stuck with their head inside.",
     False),
    ("{0} dressed up as a pirate to snatch {1}'s toy treasure chest, but it was filled with costume jewelry.", False),
    (
        "During the master plan, {0} aimed to steal {1}'s invisible doctor stethoscope, but it tickled their ears.",
        False),
    ("{0} hatched a cunning scheme to nab {1}'s pretend explorer map, but it led them in circles.", False),
    ("In a comedic twist, {0} tried to steal {1}'s collection of toy vehicles, but they all had flat tires.", False),
    ("{0} schemed to take {1}'s toy astronaut gloves, but they were too slippery to hold.", False),
    (
        "During the elaborate caper, {0} attempted to snatch {1}'s pretend scientist test tubes, but they were filled with glitter.",
        False),
    ("{0} orchestrated a plan to steal {1}'s toy detective notebook, but it was full of doodles.", False),
    ("In a daring plot, {0} tried to steal {1}'s invisible chef hat, but it turned into a feather boa.", False),
    ("{0} disguised themselves as a scientist to nab {1}'s toy lab coat, but got caught in the sleeves.", False),
    ("During the grand heist, {0} went after {1}'s pretend superhero belt, but it was too tight.", False),
    ("{0} plotted to steal {1}'s toy construction helmet, but it fell over their eyes.", False),
    ("{0} managed to stealthily swipe {1}'s collection of rubber duckies and escaped without a trace.", True),
    ("In a daring heist, {0} successfully nabbed {1}'s cookie jar and left behind a trail of crumbs.", True),
    ("{0} disguised themselves as a penguin and skillfully snatched {1}'s snow cone before melting away.", True),
    ("During the grand heist, {0} managed to unlock {1}'s invisible treasure chest and made off with the loot.", True),
    ("{0} dressed up as a ninja and swiftly took {1}'s pillow without leaving a sound.", True),
    (
        "In an audacious move, {0} pulled off a heist to steal {1}'s fake gold coins, leaving behind a note that said 'chocolate wrappers won't fool me.'",
        True),
    ("{0} successfully swiped {1}'s invisible sandwich and left a note saying 'thanks for the air.'", True),
    (
        "During the master plan, {0} cleverly outwitted {1} in a game of hide-and-seek and claimed their secret banana stash.",
        True),
    ("{0} managed to snatch {1}'s rubber chicken collection with finesse and disappeared in a puff of feathers.", True),
    (
        "In a comedic twist, {0} swiftly nabbed {1}'s invisible pet rock and left a note saying 'now I have an imaginary friend.'",
        True),
    ("{0} schemed to steal {1}'s cardboard castle, but used their cunning to outsmart the cardboard dragon.", True),
    ("In an audacious move, {0} successfully navigated through the invisible stamp collection and secured the loot.",
     True),
    ("During the elaborate caper, {0} carefully swiped {1}'s bubble wrap, leaving behind a symphony of pops.", True),
    ("{0} orchestrated a plan to take {1}'s toy spaceship and embarked on a cosmic adventure.", True),
    (
        "In a daring plot, {0} aimed to steal {1}'s toy telescope and gazed at the stars from the comfort of their hideout.",
        True),
    (
        "{0} disguised themselves as a superhero and skillfully snatched {1}'s rubber band ball before it could bounce away.",
        True),
    (
        "During the grand heist, {0} managed to outwit {1} and claimed the pretend pirate treasure, leaving behind a trail of laughter.",
        True),
    (
        "{0} plotted to steal {1}'s invisible jetpack and soared through the imaginary skies, leaving a trail of 'invisible' contrails.",
        True),
    (
        "In an audacious move, {0} successfully nabbed {1}'s pretend crown and declared themselves the ruler of the playroom.",
        True),
    ("During the master plan, {0} skillfully outmaneuvered {1}'s toy dinosaurs and made off with the prehistoric loot.",
     True),
    ("{0} hatched a cunning scheme to steal {1}'s invisible ninja sword and vanished like a shadow.", True),
    ("In a comedic twist, {0} slyly swiped {1}'s magic potion kit and concocted laughter-inducing mixtures.", True),
    ("{0} schemed to take {1}'s toy rocket and launched it on a high-flying adventure.", True),
    (
        "During the elaborate caper, {0} cleverly nabbed {1}'s pretend detective kit and left behind a trail of toy footprints as a diversion.",
        True),
    (
        "{0} orchestrated a plan to steal {1}'s collection of toy bugs, leaving behind a miniature 'bug-sized' thank-you note.",
        True),
    (
        "In a daring plot, {0} managed to outsmart {1} and secured the invisible friend's favorite toy, leaving behind a friendly wink.",
        True),
    (
        "{0} disguised themselves as a magician and skillfully swiped {1}'s magic wand, leaving behind a bouquet of rubber chickens.",
        True),
    (
        "During the grand heist, {0} cleverly swiped {1}'s toy telescope and left a note saying 'now I can see the universe.'",
        True),
    ("{0} plotted to steal {1}'s toy magic carpet and whisked themselves away on an enchanted ride.", True),
    (
        "In an audacious move, {0} successfully nabbed {1}'s collection of toy aliens and declared themselves the new extraterrestrial leader.",
        True),
    ("{0} dressed up as a knight and managed to secure {1}'s pretend knight armor, leaving behind a trail of chivalry.",
     True),
    (
        "During the master plan, {0} skillfully swiped {1}'s toy space shuttle and embarked on a mission to explore the playroom galaxy.",
        True),
    (
        "In a daring plot, {0} managed to outwit {1} and claimed the invisible pirate treasure, leaving behind a note that said 'x marks the spot.'",
        True),
    (
        "{0} disguised themselves as a chef and successfully nabbed {1}'s toy kitchen set, leaving behind a gourmet imaginary feast.",
        True),
    (
        "During the grand heist, {0} cleverly swiped {1}'s pretend explorer backpack and embarked on an imaginary adventure of their own.",
        True),
    ("{0} plotted to steal {1}'s toy spy glasses and left a cryptic note that said 'I spy with my little eye.'", True),
    (
        "In an audacious move, {0} successfully secured {1}'s collection of toy musical instruments and orchestrated a playful symphony.",
        True),
    (
        "{0} dressed up as a superhero and skillfully swiped {1}'s toy mask, leaving behind a note that said 'now I have the power.'",
        True),
    (
        "During the master plan, {0} managed to outwit {1} and claimed the invisible explorer hat, leaving behind an 'invisible' thank-you note.",
        True),
    ("{0} hatched a cunning scheme to steal {1}'s toy firefighter hose and extinguished imaginary fires all around.",
     True),
    (
        "In a comedic twist, {0} slyly swiped {1}'s toy magician's hat and left behind a trail of floating rabbits.",
        True),
    ("{0} schemed to take {1}'s collection of toy sports equipment and organized an epic playroom championship.", True),
    (
        "During the elaborate caper, {0} skillfully nabbed {1}'s pretend artist beret and created a masterpiece of silliness.",
        True),
    ("{0} orchestrated a plan to steal {1}'s toy chef apron and cooked up a feast of imagination.", True),
    (
        "In a daring plot, {0} managed to secure {1}'s invisible astronaut helmet and embarked on an intergalactic adventure.",
        True),
    (
        "{0} disguised themselves as a spy and successfully nabbed {1}'s toy magnifying glass, leaving behind a trail of mystery.",
        True),
    (
        "During the grand heist, {0} cleverly swiped {1}'s pretend scientist lab coat and concocted laughter-inducing 'potions.'",
        True),
    ("{0} plotted to steal {1}'s toy firefighter boots and left behind a trail of imaginary 'footprints.'", True),
    (
        "In an audacious move, {0} skillfully managed to secure {1}'s collection of toy building blocks and constructed a tower of imagination.",
        True),
    (
        "{0} dressed up as a magician and skillfully swiped {1}'s toy wand, leaving behind a flurry of magically appearing rubber chickens.",
        True),
    (
        "During the master plan, {0} outwitted {1} and claimed the invisible explorer hat, leaving behind an 'invisible' thank-you note.",
        True),
    ("{0} hatched a cunning scheme to steal {1}'s toy firefighter hose and extinguished imaginary fires all around.",
     True),
    (
        "In a comedic twist, {0} slyly swiped {1}'s toy magician's hat and left behind a trail of floating rabbits.",
        True),
    ("{0} schemed to take {1}'s collection of toy sports equipment and organized an epic playroom championship.", True),
    (
        "During the elaborate caper, {0} skillfully nabbed {1}'s pretend artist beret and created a masterpiece of silliness.",
        True),
    ("{0} orchestrated a plan to steal {1}'s toy chef apron and cooked up a feast of imagination.", True),
    (
        "In a daring plot, {0} managed to secure {1}'s invisible astronaut helmet and embarked on an intergalactic adventure.",
        True),
    (
        "{0} disguised themselves as a spy and successfully nabbed {1}'s toy magnifying glass, leaving behind a trail of mystery.",
        True),
    (
        "During the grand heist, {0} cleverly swiped {1}'s pretend scientist lab coat and concocted laughter-inducing 'potions.'",
        True),
    ("{0} plotted to steal {1}'s toy firefighter boots and left behind a trail of imaginary 'footprints.'", True),
    (
        "In an audacious move, {0} skillfully managed to secure {1}'s collection of toy building blocks and constructed a tower of imagination.",
        True),
    (
        "{0} dressed up as a magician and skillfully swiped {1}'s toy wand, leaving behind a flurry of magically appearing rubber chickens.",
        True),
    (
        "During the master plan, {0} skillfully managed to secure {1}'s collection of toy animals, creating a zoo of imagination.",
        True),
    ("{0} orchestrated a plan to steal {1}'s toy airplane and took an imaginary flight to new heights.", True),
    (
        "In a daring plot, {0} managed to outwit {1} and claimed the invisible knight sword, becoming the champion of the playroom.",
        True),
    (
        "{0} disguised themselves as a scientist and skillfully swiped {1}'s toy volcano, conducting 'eruptions' of laughter.",
        True),
    (
        "During the grand heist, {0} cleverly nabbed {1}'s pretend superhero mask and left behind a note saying 'I'm now the masked giggler.'",
        True),
    ("{0} plotted to steal {1}'s toy race car track and raced away with imaginary speed.", True),
    (
        "In an audacious move, {0} skillfully secured {1}'s collection of toy musical instruments, orchestrating a symphony of silliness.",
        True),
    (
        "{0} dressed up as a superhero and successfully swiped {1}'s toy cape, leaving behind a trail of invisible heroics.",
        True),
    (
        "During the master plan, {0} managed to outwit {1} and claimed the invisible pirate hat, leaving a note that said 'Arrr, I've got it now.'",
        True),
    (
        "{0} hatched a cunning scheme to steal {1}'s toy firefighter hat and extinguished imaginary blazes throughout the playroom.",
        True),
    ("In a comedic twist, {0} skillfully swiped {1}'s toy doctor kit and administered laughter-inducing 'checkups.'",
     True),
    ("{0} schemed to take {1}'s collection of toy construction vehicles and embarked on a whimsical building project.",
     True),
    (
        "During the elaborate caper, {0} cleverly nabbed {1}'s pretend scientist goggles and examined a world of silliness.",
        True),
    ("{0} orchestrated a plan to steal {1}'s toy robot dog and played fetch with an invisible ball.", True),
    (
        "In a daring plot, {0} managed to secure {1}'s invisible superhero cape and became the guardian of imaginative adventures.",
        True),
    (
        "{0} disguised themselves as a chef and skillfully swiped {1}'s toy kitchen set, creating a feast of pretend delicacies.",
        True),
    ("During the grand heist, {0} cleverly swiped {1}'s pretend explorer backpack and embarked on an imaginary quest.",
     True),
    ("{0} plotted to steal {1}'s toy spy glasses and left a note that said 'I've got my eyes on the fun.'", True),
    (
        "In an audacious move, {0} successfully secured {1}'s collection of toy musical instruments and orchestrated a symphony of silliness.",
        True),
    ("{0} dressed up as a superhero and skillfully swiped {1}'s toy mask, leaving behind a trail of invisible heroics.",
     True),
    (
        "During the master plan, {0} managed to outwit {1} and claimed the invisible explorer hat, leaving a note that said 'Discovering laughter.'",
        True),
    (
        "{0} hatched a cunning scheme to steal {1}'s toy firefighter hose and extinguished imaginary blazes throughout the playroom.",
        True),
    ("In a comedic twist, {0} skillfully swiped {1}'s toy magician's hat and left behind a trail of floating laughter.",
     True),
    ("{0} schemed to take {1}'s collection of toy sports equipment and organized an epic playroom championship.", True),
    (
        "During the elaborate caper, {0} cleverly nabbed {1}'s pretend artist beret and created a masterpiece of silliness.",
        True),
    ("{0} orchestrated a plan to steal {1}'s toy chef apron and cooked up a feast of imagination.", True),
    (
        "In a daring plot, {0} managed to secure {1}'s invisible astronaut helmet and embarked on an intergalactic adventure.",
        True),
    (
        "{0} disguised themselves as a spy and successfully nabbed {1}'s toy magnifying glass, leaving behind a trail of mystery.",
        True),
    (
        "During the grand heist, {0} cleverly swiped {1}'s pretend scientist lab coat and concocted laughter-inducing 'potions.'",
        True),
    ("{0} plotted to steal {1}'s toy firefighter boots and left behind a trail of imaginary 'footprints.'", True),
    (
        "In an audacious move, {0} skillfully managed to secure {1}'s collection of toy building blocks and constructed a tower of imagination.",
        True),
    (
        "{0} dressed up as a magician and skillfully swiped {1}'s toy wand, leaving behind a flurry of magically appearing rubber chickens.",
        True), (
        "During the master plan, {0} skillfully swiped {1}'s toy pirate hat and left a note saying 'Ahoy, matey, the caper was a success!'",
        True),
    ("{0} managed to outsmart {1} and secured the invisible superhero belt, becoming the champion of imagination.",
     True),
    ("In a daring plot, {0} skillfully nabbed {1}'s toy construction helmet and became the 'chief architect' of fun.",
     True),
    ("{0} disguised themselves as a scientist and managed to secure {1}'s toy volcano, creating eruptions of laughter.",
     True),
    (
        "During the grand heist, {0} successfully swiped {1}'s pretend artist paintbrush, leaving behind a trail of colorful creativity.",
        True),
    ("{0} plotted to steal {1}'s toy pirate hat and set sail on an imaginary treasure-seeking adventure.", True),
    (
        "In an audacious move, {0} skillfully secured {1}'s toy firefighter helmet and became the hero of playroom safety.",
        True),
    ("{0} managed to outwit {1} and claimed the pretend pirate treasure, leaving behind a map of laughter.", True),
    ("During the master plan, {0} skillfully nabbed {1}'s invisible jetpack and soared through their imagination.",
     True),
    (
        "{0} disguised themselves as a king and managed to secure {1}'s toy crown, declaring themselves the ruler of playroom fun.",
        True),
    (
        "In a daring plot, {0} skillfully swiped {1}'s collection of toy dinosaurs, leading them on an epic prehistoric adventure.",
        True),
    ("{0} orchestrated a plan to steal {1}'s toy knight armor and became the defender of the playroom kingdom.", True),
    (
        "During the grand heist, {0} cleverly managed to outwit {1} and claimed the toy space shuttle, launching their creativity into orbit.",
        True),
    (
        "{0} plotted to steal {1}'s invisible treasure chest and left behind a note that said 'I've uncovered a chest of laughter.'",
        True),
    (
        "In an audacious move, {0} skillfully secured {1}'s toy magic carpet and embarked on an imaginary journey to magical lands.",
        True),
    (
        "{0} managed to outsmart {1} and claimed the collection of toy aliens, declaring themselves the new commander of the toy universe.",
        True),
    (
        "During the master plan, {0} skillfully nabbed {1}'s pretend knight sword and became the legendary swordmaster of playroom legends.",
        True),
    (
        "{0} disguised themselves as a scientist and successfully secured {1}'s toy rocket, launching a mission to explore the unknown.",
        True),
    (
        "In a daring plot, {0} skillfully swiped {1}'s invisible pirate treasure and left behind an 'invisible' thank-you note.",
        True),
    (
        "{0} managed to outwit {1} and claimed the toy firefighter hat, becoming the fearless guardian of imaginative adventures.",
        True),
    (
        "During the grand heist, {0} cleverly swiped {1}'s toy doctor kit and left behind a note that said 'Doctor {0} reporting for fun duty!'",
        True),
    (
        "{0} plotted to steal {1}'s collection of toy construction vehicles and created a bustling playroom construction site.",
        True),
    (
        "In an audacious move, {0} skillfully secured {1}'s pretend scientist goggles and discovered a world of laughter and curiosity.",
        True),
    (
        "{0} orchestrated a plan to steal {1}'s toy robot dog and embarked on a robotic adventure through their imagination.",
        True),
    (
        "During the master plan, {0} managed to outsmart {1} and claimed the invisible superhero cape, becoming the playroom's true hero.",
        True),
    (
        "{0} disguised themselves as a chef and skillfully swiped {1}'s toy kitchen set, creating a feast of imaginative delights.",
        True),
    (
        "In a daring plot, {0} skillfully secured {1}'s pretend explorer backpack and embarked on an adventure of pretend discoveries.",
        True),
    ("{0} plotted to steal {1}'s toy spy glasses and left a note saying 'I've got my eyes on the fun!'", True),
    (
        "In an audacious move, {0} skillfully nabbed {1}'s collection of toy musical instruments and orchestrated a symphony of playroom joy.",
        True),
    ("{0} dressed up as a superhero and managed to secure {1}'s toy mask, becoming the mysterious playroom guardian.",
     True),
    (
        "During the master plan, {0} skillfully swiped {1}'s invisible explorer hat and embarked on a journey of laughter and adventure.",
        True),
    (
        "{0} managed to outwit {1} and claimed the toy firefighter hose, extinguishing imaginary fires with playful flair.",
        True),

]

funny_crime_scenarios = [
    ("{0} Attempted to steal the concept of 'personal space,' but got too close to everyone's comfort zone.", False),
    ("In a quirky move, {0} tried to steal all the 'lost socks' in town, causing laundry day chaos.", False),
    ("{0} Successfully staged a 'banana peel' heist, leaving a trail of hilarious slip-ups in their wake.", True),
    ("In a playful twist, {0} attempted to rob a prank store, but got pranked by the employees instead.", False),
    ("{0} Tried to steal the town's supply of ice cream, but the ice cream truck drove away before they could escape.",
     False),
    ("In a daring scheme, {0} tried to steal a rainbow's end, only to find a pot of glitter instead of gold.", False),
    ("{0} Attempted to rob a comedy club's open mic night, but got caught up in the laughter of the audience.", False),
    ("In an ambitious endeavor, {0} tried to steal the concept of 'good vibes,' leaving behind a trail of positivity.",
     False),
    ("{0} Successfully organized a 'silly string' heist during a parade, coating the entire route in colorful chaos.",
     True),
    (
    "In a mischievous move, {0} tried to steal a street performer's hat full of tips, but it was filled with rubber ducks.",
    False),
    ("{0} Attempted to rob a joke shop, but ended up setting off a chain reaction of laughter instead.", False),
    ("In an audacious twist, {0} tried to steal the concept of 'awkward silence,' leaving everyone speechless.", False),
    (
    "{0} Successfully staged a 'whoopie cushion' heist during a formal event, leading to unexpected bursts of laughter.",
    True),
    (
    "In a whimsical move, {0} attempted to steal a magician's top hat, but pulled out endless amounts of scarves instead.",
    False),
    ("{0} Tried to steal a cloud shaped like a treasure chest, but got rained on and lost their loot.", False),
    ("In a creative plot, {0} tried to rob a bubblegum factory, only to end up in a sticky situation.", False),
    ("{0} Attempted to steal the moon from the night sky, but ended up with a handful of stardust.", False),
    ("In a hilarious move, {0} tried to rob a hair salon, but got tangled up in their own wig collection.", False),
    ("{0} Successfully organized a 'slow-motion' heist at a snail racing event, leaving everyone in stitches.", True),
    (
    "In a playful twist, {0} attempted to steal the 'Do Not Disturb' signs from a hotel, claiming to be the master of solitude.",
    False),
    ("{0} Tried to rob a balloon animal convention, but ended up with a room full of inflated animals instead.", False),
    ("In an audacious scheme, {0} tried to steal the concept of 'Monday blues,' but ended up with a case of bad luck.",
     False),
    ("{0} Attempted to steal the Eiffel Tower during a vacation, claiming it as a 'souvenir.'", False),
    ("In a daring heist, {0} tried to steal the scent of freshly baked cookies, but ended up smelling like vanilla.",
     False),
    ("{0} Successfully staged a 'reverse robbery' where they handed out candy and balloons to bank customers.", True),
    ("In a mischievous twist, {0} tried to steal the spotlight at a comedy show, but became the punchline instead.",
     False),
    ("{0} Attempted to rob a rubber duck store, but their escape plan involved floating away in a giant rubber ducky.",
     False),
    ("In a creative move, {0} tried to steal the 'last piece of cake' from a birthday party, leading to a cake war.",
     False),
    ("{0} Successfully organized a 'pillow pet' parade during their attempt to steal a pillow factory's inventory.",
     True),
    ("In an imaginative endeavor, {0} tried to steal the concept of 'daydreaming,' leaving everyone lost in thought.",
     False),
    ("{0} Attempted to rob a tickle fight tournament, but couldn't stop laughing long enough to execute the plan.",
     False),
    ("In a whimsical twist, {0} tried to steal all the clown noses in town, causing a wave of laughter.", False),
    ("{0} Successfully organized a 'whoopie cushion' heist during an event, leaving everyone laughing in surprise.",
     True),
    (
    "In a light-hearted move, {0} tried to steal the concept of 'Monday blues,' but got stuck in a loop of fun instead.",
    False),
    ("{0} Attempted to rob a laughter yoga class, but left laughing too hard to continue.", False),
    ("In a playful endeavor, {0} tried to steal the concept of 'smiles,' leaving everyone grinning from ear to ear.",
     False),
    (
    "{0} Successfully staged a 'giant whoopie cushion' heist, leaving the city's landmarks with surprise sound effects.",
    True),
    (
    "In an audacious move, {0} tried to steal the world's largest rubber chicken, but it turned out to be an 'egg-streme' decoy.",
    False),
    ("{0} Attempted to rob a music store, but ended up leading an impromptu dance party instead.", False),
    (
    "In a whimsical twist, {0} tried to steal the concept of 'rainbows,' leaving everyone searching the sky for colors.",
    False),
    ("{0} Successfully organized a 'laughter yoga' heist, leaving everyone in fits of laughter.", True),
    ("In a quirky move, {0} attempted to steal all the 'lost socks' in town, causing laundry day chaos.", False),
    ("{0} Tried to steal the concept of 'personal space,' but got too close to everyone's comfort zone.", False),
    (
    "In a playful plot, {0} tried to steal the 'recipe for laughter' from a comedy club, but it was too secret to find.",
    False),
    ("{0} Attempted to rob a pillow fight tournament, but got caught up in the feather frenzy.", False),
    ("In a daring move, {0} tried to steal the concept of 'good vibes,' leaving behind a trail of positivity.", False),
    ("{0} Successfully organized a 'silly string' heist during a parade, coating the entire route in colorful chaos.",
     True),
    (
    "In a mischievous endeavor, {0} tried to steal a street performer's hat full of tips, but it was filled with rubber ducks.",
    False),
    ("{0} Attempted to rob a tickle fight tournament, but got caught up in the laughter and couldn't continue.", False),
    ("In a playful twist, {0} tried to steal a magician's top hat, but pulled out endless amounts of scarves instead.",
     False),
    ("{0} Successfully staged a 'banana peel' heist, leaving a trail of hilarious slip-ups in their wake.", True),
    ("In a quirky move, {0} attempted to steal the 'Lost and Found' box, claiming it as their own treasure chest.",
     False),
    ("{0} Tried to steal the town's supply of ice cream, but the ice cream truck drove away before they could escape.",
     False),
    (
    "In a whimsical scheme, {0} tried to steal the concept of 'daydreaming,' leaving everyone lost in thought.", False),
    ("{0} Successfully organized a 'pie throwing' event during their attempt to rob a bakery.", True),
    ("In a playful move, {0} tried to steal the 'last slice of pizza,' igniting a pizza-loving frenzy.", False),
    ("{0} Attempted to rob a comedy movie marathon, but got caught up in the hilarity on screen.", False),
    ("In a daring endeavor, {0} tried to steal the concept of 'tickling,' leaving everyone giggling uncontrollably.",
     False),
    ("{0} Successfully staged a 'chocolate fountain' heist, turning a party into a sweet mess.", True),
    (
    "In an imaginative move, {0} tried to steal the concept of 'daylight saving time,' leaving everyone an hour behind.",
    False),
    ("{0} Attempted to rob a balloon animal convention, but got caught in a balloon animal knot.", False),
    ("In a hilarious twist, {0} tried to steal the concept of 'Monday blues,' but everyone celebrated instead.", False),
    ("{0} Successfully organized a 'carnival game' heist, leaving the fairgrounds buzzing with laughter.", True),
    ("In a whimsical move, {0} attempted to steal a magician's wand, but could only produce rubber chickens.", False),
    (
    "{0} Tried to steal a cloud shaped like a treasure chest, but it slipped through their fingers like watercolor paint.",
    False),
    ("In a creative scheme, {0} tried to steal the 'Do Not Disturb' signs from a hotel, only to be caught napping.",
     False),
    (
    "{0} Successfully staged a 'hot dog eating contest' heist, leaving everyone with full bellies and laughter.", True),
    (
    "In a light-hearted twist, {0} attempted to steal a street performer's tip jar, but ended up juggling coins instead.",
    False),
    ("{0} Attempted to rob a laughter yoga class, but left feeling lighter than air.", False),
    ("In a playful move, {0} tried to steal the world's largest rubber band ball, but it bounced back.", False),
    ("{0} Successfully organized a 'prank war' heist, turning an ordinary day into a hilarious battleground.", True),
    ("In an audacious twist, {0} tried to steal a clown's horn, leading to a parade of honking cars.", False),
    ("{0} Attempted to rob a pillow fight flash mob, but got caught in a flurry of feathers.", False),
    (
    "In a whimsical move, {0} tried to steal a mime's invisible props, but ended up pretending to be trapped in a box.",
    False),
    ("{0} Successfully staged a 'giant bubble' heist, leaving the streets filled with floating fun.", True),
    ("In a mischievous twist, {0} tried to steal the 'Recipe for Disaster,' but it was too complicated to follow.",
     False),
    ("{0} Attempted to rob a 'bad joke' stand, but all the jokes were so bad that they ran away instead.", False),
    (
    "In a daring heist, {0} tried to steal the concept of 'awkward silence,' but ended up in an endless loop of conversation.",
    False),
    ("{0} Successfully organized a 'tug-of-war' heist, pitting laughter against seriousness.", True),
    ("In a playful move, {0} attempted to steal the 'Recipe for Happiness,' but it required too many ingredients.",
     False),
    ("{0} Attempted to rob a 'cheesy joke' competition, but the puns proved too much to handle.", False),
    ("In a comedic twist, {0} tried to steal a comedian's microphone, but all they got was feedback.", False),
    ("{0} Successfully staged a 'silly string' heist, leaving the entire city covered in vibrant chaos.", True),
    ("In a quirky move, {0} attempted to steal a street musician's tambourine, but it ended up leading a parade.",
     False),
    ("{0} Tried to steal a cloud shaped like a treasure chest, but it drifted away like a dream.", False),
    ("In a lighthearted plot, {0} tried to steal all the 'lost socks' in town, leaving everyone puzzled.", False),
    ("{0} Attempted to rob a circus, but got distracted by juggling and tightrope walking.", False),
    ("In an audacious twist, {0} tried to steal the concept of 'good vibes,' but got caught in a wave of positivity.",
     False),
    ("{0} Successfully organized a 'silly walk' heist, turning the streets into a whimsical parade.", True),
    ("In a playful move, {0} attempted to steal a mime's invisible props, but got tangled in imaginary ropes.", False),
    ("{0} Attempted to rob a 'bad joke' stand, but all the jokes were so bad that they gave up.", False),
    (
    "In a daring heist, {0} tried to steal the concept of 'awkward silence,' but ended up in an endless loop of conversations.",
    False),
    ("{0} Successfully staged a 'tug-of-war' heist, pitting laughter against seriousness.", True),
    ("In a playful move, {0} tried to steal the 'Recipe for Happiness,' but it required too many ingredients.", False),
    ("{0} Attempted to rob a 'cheesy joke' competition, but the puns proved too much to handle.", False),
    ("In a comedic twist, {0} tried to steal a comedian's microphone, but all they got was feedback.", False),
    ("{0} Successfully organized a 'silly string' heist, leaving the entire city covered in vibrant chaos.", True),
    ("In a quirky move, {0} attempted to steal a street musician's tambourine, but it ended up leading a parade.",
     False),
    ("{0} Tried to steal a cloud shaped like a treasure chest, but it drifted away like a dream.", False),
    ("In a lighthearted plot, {0} tried to steal all the 'lost socks' in town, leaving everyone puzzled.", False),
    ("{0} Attempted to rob a circus, but got distracted by juggling and tightrope walking.", False),
    ("In an audacious twist, {0} tried to steal the concept of 'good vibes,' but got caught in a wave of positivity.",
     False),
    ("{0} Successfully organized a 'silly walk' heist, turning the streets into a whimsical parade.", True),
    ("In a playful move, {0} attempted to steal a mime's invisible props, but got tangled in imaginary ropes.", False),
    ("{0} Attempted to rob a 'bad joke' stand, but all the jokes were so bad that they gave up.", False),
    (
    "In a daring heist, {0} tried to steal the concept of 'awkward silence,' but ended up in an endless loop of conversations.",
    False),
    ("{0} Successfully staged a 'tug-of-war' heist, pitting laughter against seriousness.", True),
    ("In a playful move, {0} tried to steal the 'Recipe for Happiness,' but it required too many ingredients.", False),
    ("{0} Attempted to rob a 'cheesy joke' competition, but the puns proved too much to handle.", False),
    ("In a comedic twist, {0} tried to steal a comedian's microphone, but all they got was feedback.", False),
    ("{0} Successfully organized a 'silly string' heist, leaving the entire city covered in vibrant chaos.", True),
    ("In a quirky move, {0} attempted to steal a street musician's tambourine, but it ended up leading a parade.",
     False),
    ("{0} Tried to steal a cloud shaped like a treasure chest, but it drifted away like a dream.", False),
    ("In a lighthearted plot, {0} tried to steal all the 'lost socks' in town, leaving everyone puzzled.", False),
    ("{0} Attempted to rob a circus, but got distracted by juggling and tightrope walking.", False),
    ("In an audacious twist, {0} tried to steal the concept of 'good vibes,' but got caught in a wave of positivity.",
     False),
    ("{0} Successfully organized a 'silly walk' heist, turning the streets into a whimsical parade.", True),
    ("In a playful move, {0} attempted to steal a mime's invisible props, but got tangled in imaginary ropes.", False),
    ("{0} Attempted to rob a 'bad joke' stand, but all the jokes were so bad that they gave up.", False),
    (
    "In a daring heist, {0} tried to steal the concept of 'awkward silence,' but ended up in an endless loop of conversations.",
    False),
    ("{0} Successfully staged a 'tug-of-war' heist, pitting laughter against seriousness.", True),
    ("In a playful move, {0} tried to steal the 'Recipe for Happiness,' but it required too many ingredients.", False),
    ("{0} Attempted to rob a 'cheesy joke' competition, but the puns proved too much to handle.", False),
    ("In a comedic twist, {0} tried to steal a comedian's microphone, but all they got was feedback.", False),
    ("{0} Successfully organized a 'silly string' heist, leaving the entire city covered in vibrant chaos.", True),
    ("In a quirky move, {0} attempted to steal a street musician's tambourine, but it ended up leading a parade.",
     False),
    ("{0} Tried to steal a cloud shaped like a treasure chest, but it drifted away like a dream.", False),
    ("In a lighthearted plot, {0} tried to steal all the 'lost socks' in town, leaving everyone puzzled.", False),
    ("{0} Attempted to rob a circus, but got distracted by juggling and tightrope walking.", False),
    ("In an audacious twist, {0} tried to steal the concept of 'good vibes,' but got caught in a wave of positivity.",
     False),
    ("{0} Successfully organized a 'silly walk' heist, turning the streets into a whimsical parade.", True),
    ("In a playful move, {0} attempted to steal a mime's invisible props, but got tangled in imaginary ropes.", False),
    ("{0} Attempted to rob a 'bad joke' stand, but all the jokes were so bad that they gave up.", False),
    (
    "In a daring heist, {0} tried to steal the concept of 'awkward silence,' but ended up in an endless loop of conversations.",
    False),
    ("{0} Successfully staged a 'tug-of-war' heist, pitting laughter against seriousness.", True),
    ("In a playful move, {0} tried to steal the 'Recipe for Happiness,' but it required too many ingredients.", False),
    ("{0} Attempted to rob a 'cheesy joke' competition, but the puns proved too much to handle.", False),
    ("In a comedic twist, {0} tried to steal a comedian's microphone, but all they got was feedback.", False),
    ("{0} Successfully organized a 'silly string' heist, leaving the entire city covered in vibrant chaos.", True),
    ("In a quirky move, {0} attempted to steal a street musician's tambourine, but it ended up leading a parade.",
     False),
    ("{0} Tried to steal a cloud shaped like a treasure chest, but it drifted away like a dream.", False),
    ("In a lighthearted plot, {0} tried to steal all the 'lost socks' in town, leaving everyone puzzled.", False),
    ("{0} Attempted to rob a circus, but got distracted by juggling and tightrope walking.", False),
    ("In an audacious twist, {0} tried to steal the concept of 'good vibes,' but got caught in a wave of positivity.",
     False),
    ("{0} Successfully organized a 'silly walk' heist, turning the streets into a whimsical parade.", True),
    ("In a playful move, {0} attempted to steal a mime's invisible props, but got tangled in imaginary ropes.", False),
    ("{0} Attempted to rob a 'bad joke' stand, but all the jokes were so bad that they gave up.", False),
    (
    "In a daring heist, {0} tried to steal the concept of 'awkward silence,' but ended up in an endless loop of conversations.",
    False),
    ("{0} Successfully staged a 'tug-of-war' heist, pitting laughter against seriousness.", True),
    ("In a playful move, {0} tried to steal the 'Recipe for Happiness,' but it required too many ingredients.", False),
    ("{0} Attempted to rob a 'cheesy joke' competition, but the puns proved too much to handle.", False),
    ("In a comedic twist, {0} tried to steal a comedian's microphone, but all they got was feedback.", False),
    ("{0} Successfully organized a 'silly string' heist, leaving the entire city covered in vibrant chaos.", True),
    ("In a quirky move, {0} attempted to steal a street musician's tambourine, but it ended up leading a parade.",
     False),
    ("{0} Tried to steal a cloud shaped like a treasure chest, but it drifted away like a dream.", False),
    ("In a lighthearted plot, {0} tried to steal all the 'lost socks' in town, leaving everyone puzzled.", False),
    ("{0} Attempted to rob a circus, but got distracted by juggling and tightrope walking.", False),
    ("In an audacious twist, {0} tried to steal the concept of 'good vibes,' but got caught in a wave of positivity.",
     False),
    ("{0} Successfully organized a 'silly walk' heist, turning the streets into a whimsical parade.", True),
    ("In a playful move, {0} attempted to steal a mime's invisible props, but got tangled in imaginary ropes.", False),
    ("{0} Attempted to rob a 'bad joke' stand, but all the jokes were so bad that they gave up.", False),
    (
    "In a daring heist, {0} tried to steal the concept of 'awkward silence,' but ended up in an endless loop of conversations.",
    False),
    ("{0} Successfully staged a 'tug-of-war' heist, pitting laughter against seriousness.", True),
    ("In a playful move, {0} tried to steal the 'Recipe for Happiness,' but it required too many ingredients.", False),
    ("{0} Attempted to rob a 'cheesy joke' competition, but the puns proved too much to handle.", False),
    ("In a comedic twist, {0} tried to steal a comedian's microphone, but all they got was feedback.", False),
    ("{0} Successfully organized a 'silly string' heist, leaving the entire city covered in vibrant chaos.", True),
    ("In a quirky move, {0} attempted to steal a street musician's tambourine, but it ended up leading a parade.",
     False),
    ("{0} Tried to steal a cloud shaped like a treasure chest, but it drifted away like a dream.", False),
    ("In a lighthearted plot, {0} tried to steal all the 'lost socks' in town, leaving everyone puzzled.", False),
    ("{0} Attempted to rob a circus, but got distracted by juggling and tightrope walking.", False),
    ("In an audacious twist, {0} tried to steal the concept of 'good vibes,' but got caught in a wave of positivity.",
     False),
    ("{0} Successfully organized a 'silly walk' heist, turning the streets into a whimsical parade.", True),
    ("In a playful move, {0} attempted to steal a mime's invisible props, but got tangled in imaginary ropes.", False),
    ("{0} Attempted to rob a 'bad joke' stand, but all the jokes were so bad that they gave up.", False),
    (
    "In a daring heist, {0} tried to steal the concept of 'awkward silence,' but ended up in an endless loop of conversations.",
    False),
    ("{0} Successfully staged a 'tug-of-war' heist, pitting laughter against seriousness.", True),
    ("In a playful move, {0} tried to steal the 'Recipe for Happiness,' but it required too many ingredients.", False),
    ("{0} Attempted to rob a 'cheesy joke' competition, but the puns proved too much to handle.", False),
    ("In a comedic twist, {0} tried to steal a comedian's microphone, but all they got was feedback.", False),
    ("{0} Successfully organized a 'silly string' heist, leaving the entire city covered in vibrant chaos.", True),
    ("In a quirky move, {0} attempted to steal a street musician's tambourine, but it ended up leading a parade.",
     False),
    ("{0} Tried to steal a cloud shaped like a treasure chest, but it drifted away like a dream.", False),
    ("In a lighthearted plot, {0} tried to steal all the 'lost socks' in town, leaving everyone puzzled.", False),
    ("{0} Attempted to rob a circus, but got distracted by juggling and tightrope walking.", False),
    ("In an audacious twist, {0} tried to steal the concept of 'good vibes,' but got caught in a wave of positivity.",
     False),
    ("{0} Successfully organized a 'silly walk' heist, turning the streets into a whimsical parade.", True),
    ("In a playful move, {0} attempted to steal a mime's invisible props, but got tangled in imaginary ropes.", False),
    ("{0} Attempted to rob a 'bad joke' stand, but all the jokes were so bad that they gave up.", False),
    (
    "In a daring heist, {0} tried to steal the concept of 'awkward silence,' but ended up in an endless loop of conversations.",
    False),
    ("{0} Successfully staged a 'tug-of-war' heist, pitting laughter against seriousness.", True),
    ("In a playful move, {0} tried to steal the 'Recipe for Happiness,' but it required too many ingredients.", False),
    ("{0} Attempted to rob a 'cheesy joke' competition, but the puns proved too much to handle.", False),
    ("In a comedic twist, {0} tried to steal a comedian's microphone, but all they got was feedback.", False),
    ("{0} Successfully organized a 'silly string' heist, leaving the entire city covered in vibrant chaos.", True),
    ("In a quirky move, {0} attempted to steal a street musician's tambourine, but it ended up leading a parade.",
     False),
    ("{0} Tried to steal a cloud shaped like a treasure chest, but it drifted away like a dream.", False),
    ("In a lighthearted plot, {0} tried to steal all the 'lost socks' in town, leaving everyone puzzled.", False),
    ("{0} Attempted to rob a circus, but got distracted by juggling and tightrope walking.", False),
    ("In an audacious twist, {0} tried to steal the concept of 'good vibes,' but got caught in a wave of positivity.",
     False),
    ("{0} Successfully organized a 'silly walk' heist, turning the streets into a whimsical parade.", True),
    ("In a playful move, {0} attempted to steal a mime's invisible props, but got tangled in imaginary ropes.", False),
    ("{0} Attempted to rob a 'bad joke' stand, but all the jokes were so bad that they gave up.", False),
    (
    "In a daring heist, {0} tried to steal the concept of 'awkward silence,' but ended up in an endless loop of conversations.",
    False),
    ("{0} Successfully staged a 'tug-of-war' heist, pitting laughter against seriousness.", True),
    ("In a playful move, {0} tried to steal the 'Recipe for Happiness,' but it required too many ingredients.", False),
    ("{0} Attempted to rob a 'cheesy joke' competition, but the puns proved too much to handle.", False),
    ("In a comedic twist, {0} tried to steal a comedian's microphone, but all they got was feedback.", False),
    ("{0} Successfully organized a 'silly string' heist, leaving the entire city covered in vibrant chaos.", True),
    ("In a quirky move, {0} attempted to steal a street musician's tambourine, but it ended up leading a parade.",
     False),
    ("{0} Tried to steal a cloud shaped like a treasure chest, but it drifted away like a dream.", False),
    ("In a lighthearted plot, {0} tried to steal all the 'lost socks' in town, leaving everyone puzzled.", False),
    ("{0} Attempted to rob a circus, but got distracted by juggling and tightrope walking.", False),
    ("In an audacious twist, {0} tried to steal the concept of 'good vibes,' but got caught in a wave of positivity.",
     False),
    ("{0} Successfully organized a 'silly walk' heist, turning the streets into a whimsical parade.", True),
    ("In a playful move, {0} attempted to steal a mime's invisible props, but got tangled in imaginary ropes.", False),
    ("{0} Attempted to rob a 'bad joke' stand, but all the jokes were so bad that they gave up.", False),
    (
    "In a daring heist, {0} tried to steal the concept of 'awkward silence,' but ended up in an endless loop of conversations.",
    False),
    ("{0} Successfully staged a 'tug-of-war' heist, pitting laughter against seriousness.", True),
    ("In a playful move, {0} tried to steal the 'Recipe for Happiness,' but it required too many ingredients.", False),
    ("{0} Attempted to rob a 'cheesy joke' competition, but the puns proved too much to handle.", False),
    ("In a comedic twist, {0} tried to steal a comedian's microphone, but all they got was feedback.", False),
    ("{0} Successfully organized a 'silly string' heist, leaving the entire city covered in vibrant chaos.", True),
    ("In a quirky move, {0} attempted to steal a street musician's tambourine, but it ended up leading a parade.",
     False),
    ("{0} Tried to steal a cloud shaped like a treasure chest, but it drifted away like a dream.", False),
    ("In a lighthearted plot, {0} tried to steal all the 'lost socks' in town, leaving everyone puzzled.", False),
    ("{0} Attempted to rob a circus, but got distracted by juggling and tightrope walking.", False),
    ("In an audacious twist, {0} tried to steal the concept of 'good vibes,' but got caught in a wave of positivity.",
     False),
    ("{0} Successfully organized a 'silly walk' heist, turning the streets into a whimsical parade.", True),
    ("In a playful move, {0} attempted to steal a mime's invisible props, but got tangled in imaginary ropes.", False),
    ("{0} Attempted to rob a 'bad joke' stand, but all the jokes were so bad that they gave up.", False),
    (
    "In a daring heist, {0} tried to steal the concept of 'awkward silence,' but ended up in an endless loop of conversations.",
    False),
    ("{0} Successfully staged a 'tug-of-war' heist, pitting laughter against seriousness.", True),
    ("In a playful move, {0} tried to steal the 'Recipe for Happiness,' but it required too many ingredients.", False),
    ("{0} Attempted to rob a 'cheesy joke' competition, but the puns proved too much to handle.", False),
    ("In a comedic twist, {0} tried to steal a comedian's microphone, but all they got was feedback.", False),
    ("{0} Successfully organized a 'silly string' heist, leaving the entire city covered in vibrant chaos.", True),
    ("In a quirky move, {0} attempted to steal a street musician's tambourine, but it ended up leading a parade.",
     False),
    ("{0} Tried to steal a cloud shaped like a treasure chest, but it drifted away like a dream.", False),
    ("In a lighthearted plot, {0} tried to steal all the 'lost socks' in town, leaving everyone puzzled.", False),
    ("{0} Attempted to rob a circus, but got distracted by juggling and tightrope walking.", False),
    ("In an audacious twist, {0} tried to steal the concept of 'good vibes,' but got caught in a wave of positivity.",
     False),
    ("{0} Successfully organized a 'silly walk' heist, turning the streets into a whimsical parade.", True),
    ("In a playful move, {0} attempted to steal a mime's invisible props, but got tangled in imaginary ropes.", False),
    ("{0} Attempted to rob a 'bad joke' stand, but all the jokes were so bad that they gave up.", False),
    (
    "In a daring heist, {0} tried to steal the concept of 'awkward silence,' but ended up in an endless loop of conversations.",
    False),
    ("{0} Successfully staged a 'tug-of-war' heist, pitting laughter against seriousness.", True),
    ("In a playful move, {0} tried to steal the 'Recipe for Happiness,' but it required too many ingredients.", False),
    ("{0} Attempted to rob a 'cheesy joke' competition, but the puns proved too much to handle.", False),
    ("In a comedic twist, {0} tried to steal a comedian's microphone, but all they got was feedback.", False),
    ("{0} Successfully organized a 'silly string' heist, leaving the entire city covered in vibrant chaos.", True),
    ("In a quirky move, {0} attempted to steal a street musician's tambourine, but it ended up leading a parade.",
     False),
    ("{0} Tried to steal a cloud shaped like a treasure chest, but it drifted away like a dream.", False),
    ("In a lighthearted plot, {0} tried to steal all the 'lost socks' in town, leaving everyone puzzled.", False),
    ("{0} Attempted to rob a circus, but got distracted by juggling and tightrope walking.", False),
    ("In an audacious twist, {0} tried to steal the concept of 'good vibes,' but got caught in a wave of positivity.",
     False),
    ("{0} Successfully organized a 'silly walk' heist, turning the streets into a whimsical parade.", True),
    ("In a playful move, {0} attempted to steal a mime's invisible props, but got tangled in imaginary ropes.", False),
    ("{0} Attempted to rob a 'bad joke' stand, but all the jokes were so bad that they gave up.", False),
    (
    "In a daring heist, {0} tried to steal the concept of 'awkward silence,' but ended up in an endless loop of conversations.",
    False),
    ("{0} Successfully staged a 'tug-of-war' heist, pitting laughter against seriousness.", True),
    ("In a playful move, {0} tried to steal the 'Recipe for Happiness,' but it required too many ingredients.", False),
    ("{0} Attempted to rob a 'cheesy joke' competition, but the puns proved too much to handle.", False),
    ("In a comedic twist, {0} tried to steal a comedian's microphone, but all they got was feedback.", False),
    ("{0} Successfully organized a 'silly string' heist, leaving the entire city covered in vibrant chaos.", True)]
